name: homestri-ur5e-rl
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - tqdm
  - opencv
  - pillow
  - imageio
  - ffmpeg
  - git
  
  # CUDA and PyTorch (CUDA 12.1 compatible with your RTX 4060)
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  
  # MuJoCo and robotics
  - conda-forge::mujoco>=2.3.0
  
  # Jupyter for analysis
  - jupyter
  - notebook
  - ipykernel
  
  # Development tools
  - black
  - flake8
  
  - pip:
    # Reinforcement Learning
    - gymnasium>=0.29.0
    - stable-baselines3>=2.0.0
    - sb3-contrib
    - tensorboard
    - wandb
    
    # Additional utilities
    - imageio-ffmpeg
    - moviepy
    
    # Install homestri-ur5e-rl in development mode
    - -e .
