# M2 Pro Optimized Configuration
# Hardware: M2 Pro 12-core, 19-core GPU, 16GB RAM
# Target: Stable training with 70%+ real-world success rate

environment:
  n_envs: 1
  camera_resolution: 64
  frame_skip: 5
  xml_file: "custom_scene.xml"
  control_mode: "joint"
  use_stuck_detection: true
  use_domain_randomization: false  # PROGRESSIVE FIX: Start with no randomization, enable progressively via curriculum
  initial_curriculum_level: 0.05  # PROGRESSIVE FIX: Start with milestone_0 (NEAR SPAWN)
  render_mode: null
  
training:
  total_timesteps: 300_000  # PROGRESSIVE CURRICULUM: Extended to allow full approach milestone progression
  learning_rate: 0.0001  # CATASTROPHIC FORGETTING FIX: Reduced from 0.0003 to prevent aggressive updates
  n_steps: 512  # a bit larger for stabler gradients
  batch_size: 256  # match n_steps
  n_epochs: 3  # CATASTROPHIC FORGETTING FIX: Reduced from 4 to prevent over-optimization
  gamma: 0.995  # FIXED: Increased for longer-term planning
  gae_lambda: 0.95
  clip_range: 0.15  # CATASTROPHIC FORGETTING FIX: Much smaller range to prevent policy destruction
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01  # CATASTROPHIC FORGETTING FIX: Much lower to prioritize exploitation over exploration
  vf_coef: 0.5
  max_grad_norm: 0.3  # CATASTROPHIC FORGETTING FIX: Tighter clipping to prevent large updates
  target_kl: 0.008  # CATASTROPHIC FORGETTING FIX: Very conservative to prevent policy divergence
  use_sde: false  # CATASTROPHIC FORGETTING FIX: Disable SDE to reduce policy noise
  sde_sample_freq: 4
  detailed_log_freq: 1600  # REDUCED: matches new n_steps
  device: "mps"
  num_threads: 8

evaluation:
  eval_freq: 10000  # TESTING: More frequent evaluation
  n_eval_episodes: 10  # EVAL FIX: Increased from 5 to get more reliable statistics
  deterministic: false  # EVAL FIX: Use stochastic policy to match training behavior

logging:
  save_freq: 40000  # REDUCED: matches new n_steps (100x400)
  log_interval: 10
  reset_num_timesteps: false
  tb_log_name: "ur5e_stable"
  
curriculum:
  enable: true
  success_threshold: 0.20  # Keep 20% threshold as requested
  phases:
    - name: "approach"
      description: "Learn safe approaching and distance reduction"
      timesteps: 1_000_000
      focus: "distance_reduction_without_collision"
    - name: "contact"
      description: "Learn gentle contact and basic manipulation"
      timesteps: 1_500_000
      focus: "gripper_object_contact"
    - name: "grasp"
      description: "Learn reliable grasping"
      timesteps: 1_500_000
      focus: "object_lifting"
    - name: "manipulate"
      description: "Complete pick and place tasks"
      timesteps: 1_000_000
      focus: "task_completion"

reward_structure:
  distance_reward_scale: 1.5  # CRITICAL FIX: Increased to encourage approach learning
  approach_bonus: 0.3  # CRITICAL FIX: Increased from 0.1 to better reward close approaches
  contact_bonus: 1.0  # CRITICAL FIX: Increased from 0.5 to strongly reward contact
  grasp_bonus: 3.0  # CRITICAL FIX: Increased from 2.0 to strongly reward grasping
  lift_bonus: 2.0  # CRITICAL FIX: Increased from 1.0 
  place_bonus: 5.0
  success_bonus: 10.0
  time_penalty: -0.0005  # CRITICAL FIX: Reduced penalty to allow more exploration time
  energy_penalty: -0.00005  # CRITICAL FIX: Reduced penalty to allow more movement
  velocity_penalty_threshold: 1.2  # CRITICAL FIX: Increased threshold for faster movements
  velocity_penalty_scale: -0.05  # CRITICAL FIX: Reduced penalty
  physics_violation_penalty: -1.0
  stuck_penalty: -0.3  # CRITICAL FIX: Reduced penalty to be less punitive during learning
  reward_clip_min: -20.0
  reward_clip_max: 20.0

action_limits:
  max_joint_velocity: 0.25  # STABILITY FIX: Reduced from 0.4 to prevent instability
  max_action_magnitude: 0.08  # STABILITY FIX: Reduced from 0.15 to prevent large jumps
  action_scale: 0.02  # STABILITY FIX: Reduced from 0.03 for smoother control
  action_smoothing_factor: 0.4  # STABILITY FIX: Increased from 0.2 for more smoothing
  max_consecutive_physics_errors: 3

physics:
  timestep: 0.002
  iterations: 50
  solver: "Newton"
  jacobian: "sparse"
  tolerance: 1e-10
  joint_damping: 1.0
  joint_armature: 0.01
  joint_frictionloss: 0.2
  contact_solimp: [0.9, 0.9, 0.01]
  contact_solref: [0.005, 1]
  contact_margin: 0.001

camera:
  realsense_rgb_fov_h: 69.0
  realsense_rgb_fov_v: 42.0
  realsense_depth_fov_h: 87.0
  realsense_depth_fov_v: 58.0
  min_depth: 0.28
  max_depth: 3.0
  
safety:
  enable_physics_checks: true
  enable_workspace_bounds: true
  enable_joint_limits: true
  enable_velocity_limits: true
  terminate_on_physics_error: true