environment:
  n_envs: 1
  camera_resolution: 64
  frame_skip: 5
  xml_file: "custom_scene.xml"
  control_mode: "joint"
  use_stuck_detection: true
  use_domain_randomization: false
  initial_curriculum_level: 0.05
  render_mode: null
  
training:
  total_timesteps: 1_000_000
  learning_rate: 0.0001
  n_steps: 512
  batch_size: 256
  n_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_range: 0.15
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.3
  target_kl: 0.008
  use_sde: false
  sde_sample_freq: 4
  detailed_log_freq: 1600
  device: "mps"
  num_threads: 8

evaluation:
  eval_freq: 10000
  n_eval_episodes: 10
  deterministic: false

logging:
  save_freq: 40000
  log_interval: 10
  reset_num_timesteps: false
  tb_log_name: "ur5e_stable"
  
curriculum:
  enable: true
  success_threshold: 0.20
  phases:
    - name: "approach"
      description: "Learn safe approaching and distance reduction"
      timesteps: 1_000_000
      focus: "distance_reduction_without_collision"
    - name: "contact"
      description: "Learn gentle contact and basic manipulation"
      timesteps: 1_500_000
      focus: "gripper_object_contact"
    - name: "grasp"
      description: "Learn reliable grasping"
      timesteps: 1_500_000
      focus: "object_lifting"
    - name: "manipulate"
      description: "Complete pick and place tasks"
      timesteps: 1_000_000
      focus: "task_completion"

reward_structure:
  distance_reward_scale: 1.5
  approach_bonus: 0.3
  contact_bonus: 1.0
  grasp_bonus: 3.0
  lift_bonus: 2.0
  place_bonus: 5.0
  success_bonus: 10.0
  time_penalty: -0.0005
  energy_penalty: -0.00005
  velocity_penalty_threshold: 1.2
  velocity_penalty_scale: -0.05
  physics_violation_penalty: -1.0
  stuck_penalty: -0.3
  reward_clip_min: -20.0
  reward_clip_max: 20.0

action_limits:
  max_joint_velocity: 0.25
  max_action_magnitude: 0.08
  action_scale: 0.02
  action_smoothing_factor: 0.4
  max_consecutive_physics_errors: 3

physics:
  timestep: 0.002
  iterations: 50
  solver: "Newton"
  jacobian: "sparse"
  tolerance: 1e-10
  joint_damping: 1.0
  joint_armature: 0.01
  joint_frictionloss: 0.2
  contact_solimp: [0.9, 0.9, 0.01]
  contact_solref: [0.005, 1]
  contact_margin: 0.001

camera:
  realsense_rgb_fov_h: 69.0
  realsense_rgb_fov_v: 42.0
  realsense_depth_fov_h: 87.0
  realsense_depth_fov_v: 58.0
  min_depth: 0.28
  max_depth: 3.0
  
safety:
  enable_physics_checks: true
  enable_workspace_bounds: true
  enable_joint_limits: true
  enable_velocity_limits: true
  terminate_on_physics_error: true