# RTX 4060 Optimized Configuration
# Hardware: RTX 4060 8GB, 16GB RAM, Ryzen 5, Ubuntu 24.04
# Target: Multi-day stable training with 70%+ real-world success rate

environment:
  n_envs: 4 # Increased for better throughput while maintaining stability

  camera_resolution: 64  # Proven stable from M2 validation, also change later (old 64)

  frame_skip: 5
  xml_file: "custom_scene.xml"
  control_mode: "joint"
  use_stuck_detection: true
  
  use_domain_randomization: false 
  
  initial_curriculum_level: 0.1  
  render_mode: null  # Completely disable rendering
  headless: true  
training:
  total_timesteps: 27_000_000
  learning_rate: 0.00005  # EMERGENCY: Halve learning rate (was 0.0001)
  detailed_log_freq: 2048

  n_steps: 512

  batch_size: 32
  gradient_accumulation_steps: 4  
  
  n_epochs: 5  # REDUCED: Less aggressive updates (was 10)
  gamma: 0.99  
  gae_lambda: 0.95  
  clip_range: 0.05  # REDUCED: Much tighter clipping (was 0.1)
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.0005  # REDUCED: Less exploration (was 0.001)
  vf_coef: 1.0  # INCREASED: Help value function recover (was 0.5)
  max_grad_norm: 0.05  # REDUCED: Much stronger gradient clipping (was 0.1)
  
  target_kl: 0.01  # REDUCED: Tighter KL constraint (was 0.03)  
  
  use_mixed_precision: true
  mixed_precision_dtype: "bfloat16"  
  optimizer_offload: true  
  
  device: "cuda"
  num_threads: 4 

evaluation:
  eval_freq: 25_600 
  n_eval_episodes: 10  
  deterministic: true

logging:
  save_freq: 12_800  
  checkpoint_keep: 5 
  log_interval: 5 
  reset_num_timesteps: false
  tb_log_name: "ur5e_rtx4060"
  
  log_memory_usage: true
  memory_profile_freq: 25_600 

curriculum:
  enable: true
  
  success_threshold: 0.7 
  
  phases:
    - name: "approach_learning"
      description: "Learn safe object approach"
      timesteps: 5_000_000  
      success_threshold: 0.1  # 10% - Critical missing threshold!
      domain_randomization_level: 0.0
      
    - name: "contact_refinement" 
      description: "Refine gripper positioning and contact"
      timesteps: 4_000_000
      success_threshold: 0.3  # 30% - Critical missing threshold!
      domain_randomization_level: 0.2  
      
    - name: "grasping"
      description: "Master object grasping and lifting"
      timesteps: 8_000_000
      success_threshold: 0.5  # 50% - Critical missing threshold!
      domain_randomization_level: 0.4
      
    - name: "manipulation"
      description: "Complete pick and place tasks"
      timesteps: 6_000_000
      success_threshold: 0.7  # 70% - Critical missing threshold!
      domain_randomization_level: 0.7
      
    - name: "mastery"
      description: "Achieve robust, collision-free manipulation"
      timesteps: 4_000_000
      success_threshold: 0.85  # 85% - Critical missing threshold!
      domain_randomization_level: 1.0 

domain_randomization:
  visual:
    hsv_shift_range: [-0.1, 0.1]  
    texture_randomize_prob: 0.2  
    lighting_intensity_range: [0.8, 1.2]  
    camera_noise_std: 0.01  
    
  physical:
    mass_range: [0.8, 1.2]  
    friction_range: [0.5, 1.5]  
    damping_range: [0.95, 1.05]  
    
  enable_adr: true
  adr_performance_threshold: 0.8
  adr_expansion_rate: 0.05  
  adr_update_freq: 100_000

memory_optimization:
  pytorch_cuda_alloc_conf:
    expandable_segments: true  
    max_split_size_mb: 128
    garbage_collection_threshold: 0.7
    
  buffer_device: "cpu" 
  enable_memory_profiler: true
  auto_restart_on_oom: true 
  memory_limit_gb: 7.0  # INCREASED: 4 envs need more GPU memory (was 6.0)  

vectorization:
  vec_env_type: "SubprocVecEnv"  
  start_method: "forkserver"  
  cpu_affinity: true
  worker_cpu_cores: [0, 1, 2, 3]  # UPDATED: 4 cores for 4 environments 

monitoring:
  track_explained_variance: true
  track_kl_divergence: true
  gpu_utilization_log: true
  
  # ENHANCED: Early warning system for policy collapse
  alert_thresholds:
    kl_divergence_max: 0.02  # REDUCED: Stricter KL monitoring (was 0.05)
    explained_variance_min: 0.8  # INCREASED: Higher quality threshold (was 0.5)
    action_diversity_max: 2.0  # NEW: Detect action explosion early
    policy_std_max: 5.0  # NEW: Prevent policy standard deviation explosion
    gpu_memory_percent_max: 75 

checkpointing:
  checkpoint_freq: 12_800 
  keep_last_n: 5
  milestone_checkpoints: [1_000_000, 5_000_000, 15_000_000, 27_000_000]
  auto_resume: true
  verify_checkpoint_integrity: true

expected_performance:
  steps_per_second: 160-240  # UPDATED: Based on 4 envs performance
  episodes_per_hour: 320-480  # UPDATED: Scaled for 4 environments
  
  # Updated timeline estimates for 4 environments
  approach_learning: "7-10 hours"  # 5M steps (was 10-14 for 3 envs)
  contact_refinement: "13-17 hours"  # 9M steps total (was 17-23)
  grasping: "23-28 hours"  # 17M steps total (was 30-37)
  manipulation: "32-38 hours"  # 23M steps total (was 43-50)
  mastery: "43-47 hours"  # 27M steps total (was 57-63)
  
  gpu_memory: "6.5-7.0GB"  # UPDATED: 4 envs use more memory
  system_ram: "9-11GB"  # UPDATED: 4 envs use more RAM 

hardware:
  gpu_memory_fraction: 0.85  # INCREASED: 4 envs need more GPU memory (was 0.75)
  cpu_workers: 4  # UPDATED: Match number of environments (was 2)
  prefetch_factor: 2

validation_targets:
  physics_stability: ">99.5%" 
  reward_range: "[-10, +50]"    
  collision_rate: "<0.1%"       
  success_progression:
    approach_learning: "10%"   
    contact_refinement: "30%"   
    grasping: "50%"            
    manipulation: "70%"        
    mastery: "85%"             

design_philosophy:
  stability_priority: "M2 proven settings take precedence"
  memory_safety: "Prevent RTX 4060 bottlenecks"
  progressive_scaling: "Start conservative, expand capabilities"
  multi_day_resilience: "Prevent training collapse"
  sim_to_real_focus: "Balanced approach for real robot transfer"

camera:
  realsense_rgb_fov_h: 69.0
  realsense_rgb_fov_v: 42.0
  realsense_depth_fov_h: 87.0
  realsense_depth_fov_v: 58.0
  min_depth: 0.28
  max_depth: 3.0
  
safety:
  enable_physics_checks: true
  enable_workspace_bounds: true
  enable_joint_limits: true
  enable_velocity_limits: true
  terminate_on_physics_error: true

action_limits:
  max_joint_velocity: 0.3
  max_action_magnitude: 0.1
  action_scale: 0.02
  action_smoothing_factor: 0.3
  max_consecutive_physics_errors: 3

physics:
  timestep: 0.002
  iterations: 50
  solver: "Newton"
  jacobian: "sparse"
  tolerance: 1e-10
  joint_damping: 1.0
  joint_armature: 0.01
  joint_frictionloss: 0.2
  contact_solimp: [0.9, 0.9, 0.01]
  contact_solref: [0.005, 1]
  contact_margin: 0.001