# RTX 4060 Fixed Configuration
# Addresses KL divergence explosion and 0% success rate
# Hardware: RTX 4060 8GB, 16GB RAM, Ryzen 5

environment:
  n_envs: 4  # 4 parallel environments for RTX 4060
  camera_resolution: 64
  frame_skip: 5
  xml_file: "custom_scene.xml"
  control_mode: "joint"
  use_stuck_detection: true
  use_domain_randomization: false  # Start without randomization
  initial_curriculum_level: 0.1
  render_mode: null
  headless: false

training:
  total_timesteps: 27_000_000
  
  # CRITICAL FIXES for stability
  learning_rate: 0.00001  # 5x lower than your current (was 0.00005)
  n_steps: 2048  # 4x larger (was 512)
  batch_size: 128  # 4x larger (was 32)
  
  n_epochs: 4  # Fewer updates per batch (was 5)
  gamma: 0.99
  gae_lambda: 0.95
  
  # Relaxed clipping for stability
  clip_range: 0.1  # 2x larger (was 0.05)
  clip_range_vf: 0.1  # Added value function clipping
  
  normalize_advantage: true
  
  # Better exploration
  ent_coef: 0.005  # 10x higher (was 0.0005)
  vf_coef: 0.5  # Reduced (was 1.0)
  
  # Gradient clipping
  max_grad_norm: 0.5  # 10x higher (was 0.05)
  
  # KL constraint
  target_kl: 0.02  # 2x higher (was 0.01)
  
  # SDE for exploration
  use_sde: true
  sde_sample_freq: 4
  
  # Mixed precision disabled for stability
  use_mixed_precision: false
  
  device: "cuda"
  num_threads: 4
  detailed_log_freq: 2048

evaluation:
  eval_freq: 25_600  # Every ~6k steps per env
  n_eval_episodes: 20  # More episodes for accurate metrics
  deterministic: true

logging:
  save_freq: 51_200
  checkpoint_keep: 10
  log_interval: 5
  reset_num_timesteps: false
  tb_log_name: "ur5e_fixed"

curriculum:
  enable: true
  success_threshold: 0.05  # Lower global threshold
  
  phases:
    - name: "approach_learning"
      description: "Learn to approach and contact objects"
      timesteps: 3_000_000
      success_threshold: 0.005  # Just 0.5% to advance!
      domain_randomization_level: 0.0
      focus: "distance_reduction_and_contact"
      
    - name: "contact_refinement"
      description: "Refine contact and gripper control"
      timesteps: 3_000_000
      success_threshold: 0.05  # 5% to advance
      domain_randomization_level: 0.1
      focus: "stable_contact_and_gripper_control"
      
    - name: "grasping"
      description: "Learn to grasp objects"
      timesteps: 6_000_000
      success_threshold: 0.20  # 20% to advance
      domain_randomization_level: 0.3
      focus: "successful_grasping"
      
    - name: "manipulation"
      description: "Complete pick and place tasks"
      timesteps: 10_000_000
      success_threshold: 0.50  # 50% to advance
      domain_randomization_level: 0.5
      focus: "full_task_completion"
      
    - name: "mastery"
      description: "Achieve robust performance"
      timesteps: 5_000_000
      success_threshold: 0.70  # 70% target
      domain_randomization_level: 0.8
      focus: "efficiency_and_robustness"

reward_structure:
  # Distance guidance (primary signal)
  distance_reward_scale: 5.0
  
  # Milestone bonuses
  approach_bonus: 2.0      # < 10cm
  contact_bonus: 5.0       # < 5cm
  grasp_bonus: 20.0        # Successfully grasped
  lift_bonus: 10.0         # Lifted > 5cm
  place_bonus: 30.0        # At target location
  success_bonus: 50.0      # Task complete
  
  # Minimal penalties
  time_penalty: -0.01
  energy_penalty: 0.0      # Removed
  velocity_penalty_threshold: 2.0
  velocity_penalty_scale: -0.01
  physics_violation_penalty: -5.0
  stuck_penalty: -0.5

action_limits:
  max_joint_velocity: 0.2  # Reduced (was 0.3)
  max_action_magnitude: 0.05  # Halved (was 0.1)
  action_scale: 0.01  # Halved (was 0.02)
  action_smoothing_factor: 0.5  # More smoothing (was 0.3)
  max_consecutive_physics_errors: 5  # More tolerance

physics:
  timestep: 0.002
  iterations: 50
  solver: "Newton"
  jacobian: "sparse"
  tolerance: 1e-10
  joint_damping: 1.0
  joint_armature: 0.01
  joint_frictionloss: 0.2
  contact_solimp: [0.9, 0.95, 0.001]
  contact_solref: [0.02, 1]
  contact_margin: 0.001

camera:
  realsense_rgb_fov_h: 69.0
  realsense_rgb_fov_v: 42.0
  realsense_depth_fov_h: 87.0
  realsense_depth_fov_v: 58.0
  min_depth: 0.28
  max_depth: 3.0

safety:
  enable_physics_checks: true
  enable_workspace_bounds: true
  enable_joint_limits: true
  enable_velocity_limits: true
  terminate_on_physics_error: true

memory_optimization:
  pytorch_cuda_alloc_conf:
    expandable_segments: true
    max_split_size_mb: 128
    garbage_collection_threshold: 0.7
  
  buffer_device: "cuda"  # Keep on GPU for 4 envs
  enable_memory_profiler: false
  memory_limit_gb: 7.0

expected_timeline:
  first_contacts: "100k-500k steps"
  first_grasps: "3M-6M steps"
  50_percent_success: "12M-18M steps"
  70_percent_success: "20M-25M steps"